version: '3.8'

services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8015 --workers 2 app:server
    expose:
      - 8015
  
  app2:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8020 --workers 2 app:server
    expose:
      - 8020

  nginx:
      build: ./nginx
      ports:
        - 8015:8015
        - 8020:8020
      depends_on:
        - app1
        - app2